print('Olá mundo.')
print('Olá, como você se chama?')
print('Eu me chamo Thayna, o que está fazendo agora?')
print('Estou pensando no que cozinhar, porque?')
print('Posso da uma sugestão de comida?')
print('Pode sim, eu pensei numa sobremesa.')
print('Que tal uma trufa com morango.')
print('Gostei da sugestão, muito obrigado.')
print('Denada,bom eu tenho que ir.')
print('Ok,espero te ver novamente.')